import type { Config } from "tailwindcss"

import defaultThemePreset from "./tailwind-theme-preset"

const sansFallback = `ui-sans-serif, system-ui, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"`
const serifFallback = `ui-serif, Georgia, Cambria, "Times New Roman", Times, serif`

export default {
  darkMode: ["selector"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    container: {
      padding: "2rem",
      center: true,
    },
    screens: {
      "2xs": "360px",
      xs: "480px",
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1640px",
    },
    extend: {
      transitionTimingFunction: {
        ease: "ease",
        "in-out-quart": "cubic-bezier(0.77, 0, 0.175, 1)",
        "in-out-expo": "cubic-bezier(1, 0, 0, 1)",
        "in-expo": "cubic-bezier(0.95, 0.05, 0.795, 0.035)",
        "snappy-out": "cubic-bezier(0.19, 1, 0.22, 1)",
      },
      spacing: {
        "4.5": "1.125rem",
        "7.5": "1.875rem",
        "18": "4.5rem",
      },
      borderWidth: {
        "3": "3px",
        "5": "5px",
      },
      height: {
        "base-input-size-1": "var(--base-input-size-1-height)",
        "base-input-size-2": "var(--base-input-size-2-height)",
        "base-input-size-3": "var(--base-input-size-3-height)",
        "base-input-size-4": "var(--base-input-size-4-height)",
        "base-toggle-size-1": "var(--base-toggle-size-1-height)",
        "base-toggle-size-2": "var(--base-toggle-size-2-height)",
        "base-toggle-size-3": "var(--base-toggle-size-3-height)",
        "base-toggle-size-4": "var(--base-toggle-size-4-height)",
        // temp
        "base-button-size-1": "var(--base-button-size-1-height)",
        "base-button-size-2": "var(--base-button-size-2-height)",
        "base-button-size-3": "var(--base-button-size-3-height)",
        "base-button-size-4": "var(--base-button-size-4-height)",
      },
      width: {
        "base-toggle-size-1": "var(--base-toggle-size-1-height)",
        "base-toggle-size-2": "var(--base-toggle-size-2-height)",
        "base-toggle-size-3": "var(--base-toggle-size-3-height)",
        "base-toggle-size-4": "var(--base-toggle-size-4-height)",
      },
      ringWidth: {
        "3": "3px",
        "5": "5px",
      },
      ringOffsetWidth: {
        "3": "3px",
        "5": "5px",
        "6": "6px",
        "10": "10px",
      },
      outlineOffset: {
        "-2": "-2px",
        "-1": "-1px",
        "1.5": "1.5px",
      },
      borderRadius: {
        none: "var(--radius-none)",
        xs: "var(--radius-xs)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
        "3xl": "var(--radius-3xl)",
        full: "var(--radius-full)",
      },
      fontSize: {
        1: "var(--font-size-1)",
        2: "var(--font-size-2)",
        3: "var(--font-size-3)",
        4: "var(--font-size-4)",
        5: "var(--font-size-5)",
        6: "var(--font-size-6)",
        7: "var(--font-size-7)",
        8: "var(--font-size-8)",
        9: "var(--font-size-9)",
      },
      lineHeight: {
        1: "var(--line-height-1)",
        2: "var(--line-height-2)",
        3: "var(--line-height-3)",
        4: "var(--line-height-4)",
        5: "var(--line-height-5)",
        6: "var(--line-height-6)",
        7: "var(--line-height-7)",
        8: "var(--line-height-8)",
        9: "var(--line-height-9)",
      },
      letterSpacing: {
        1: "var(--letter-spacing-1)",
        2: "var(--letter-spacing-2)",
        3: "var(--letter-spacing-3)",
        4: "var(--letter-spacing-4)",
        5: "var(--letter-spacing-5)",
        6: "var(--letter-spacing-6)",
        7: "var(--letter-spacing-7)",
        8: "var(--letter-spacing-8)",
        9: "var(--letter-spacing-9)",
      },
      fontFamily: {
        sans: [`var(--font-geist-sans, ${sansFallback})`],
        serif: [`var(--font-serif, ${serifFallback})`],
        mono: ["var(--font-geist-mono)"],
      },
      colors: {
        primary: {
          1: "var(--primary-1)",
          2: "var(--primary-2)",
          3: "var(--primary-3)",
          4: "var(--primary-4)",
          5: "var(--primary-5)",
          6: "var(--primary-6)",
          7: "var(--primary-7)",
          8: "var(--primary-8)",
          9: "var(--primary-9)",
          10: "var(--primary-10)",
          11: "var(--primary-11)",
          12: "var(--primary-12)",
          a1: "var(--primary-a1)",
          a2: "var(--primary-a2)",
          a3: "var(--primary-a3)",
          a4: "var(--primary-a4)",
          a5: "var(--primary-a5)",
          a6: "var(--primary-a6)",
          a7: "var(--primary-a7)",
          a8: "var(--primary-a8)",
          a9: "var(--primary-a9)",
          a10: "var(--primary-a10)",
          a11: "var(--primary-a11)",
          a12: "var(--primary-a12)",
          contrast: "var(--primary-contrast)",
          surface: "var(--primary-surface)",
          indicator: "var(--primary-indicator)",
          track: "var(--primary-track)",
          DEFAULT: "var(--primary-9)",
          foreground: "var(--primary-12)",
        },
        secondary: {
          1: "var(--secondary-1)",
          2: "var(--secondary-2)",
          3: "var(--secondary-3)",
          4: "var(--secondary-4)",
          5: "var(--secondary-5)",
          6: "var(--secondary-6)",
          7: "var(--secondary-7)",
          8: "var(--secondary-8)",
          9: "var(--secondary-9)",
          10: "var(--secondary-10)",
          11: "var(--secondary-11)",
          12: "var(--secondary-12)",
          a1: "var(--secondary-a1)",
          a2: "var(--secondary-a2)",
          a3: "var(--secondary-a3)",
          a4: "var(--secondary-a4)",
          a5: "var(--secondary-a5)",
          a6: "var(--secondary-a6)",
          a7: "var(--secondary-a7)",
          a8: "var(--secondary-a8)",
          a9: "var(--secondary-a9)",
          a10: "var(--secondary-a10)",
          a11: "var(--secondary-a11)",
          a12: "var(--secondary-a12)",
          contrast: "var(--secondary-contrast)",
          surface: "var(--secondary-surface)",
          indicator: "var(--secondary-indicator)",
          track: "var(--secondary-track)",
          DEFAULT: "var(--secondary-9)",
          foreground: "var(--secondary-12)",
        },
        surface: {
          1: "var(--surface-1)",
          2: "var(--surface-2)",
          3: "var(--surface-3)",
          4: "var(--surface-4)",
          5: "var(--surface-5)",
          6: "var(--surface-6)",
          7: "var(--surface-7)",
          8: "var(--surface-8)",
          9: "var(--surface-9)",
          10: "var(--surface-10)",
          11: "var(--surface-11)",
          12: "var(--surface-12)",
          a1: "var(--surface-a1)",
          a2: "var(--surface-a2)",
          a3: "var(--surface-a3)",
          a4: "var(--surface-a4)",
          a5: "var(--surface-a5)",
          a6: "var(--surface-a6)",
          a7: "var(--surface-a7)",
          a8: "var(--surface-a8)",
          a9: "var(--surface-a9)",
          a10: "var(--surface-a10)",
          a11: "var(--surface-a11)",
          a12: "var(--surface-a12)",
          contrast: "var(--surface-contrast)",
          surface: "var(--surface-surface)",
          indicator: "var(--surface-indicator)",
          track: "var(--surface-track)",
          DEFAULT: "var(--surface-9)",
          backdrop: "var(--surface-backdrop)",
        },
        info: {
          1: "var(--info-1)",
          2: "var(--info-2)",
          3: "var(--info-3)",
          4: "var(--info-4)",
          5: "var(--info-5)",
          6: "var(--info-6)",
          7: "var(--info-7)",
          8: "var(--info-8)",
          9: "var(--info-9)",
          10: "var(--info-10)",
          11: "var(--info-11)",
          12: "var(--info-12)",
          a1: "var(--info-a1)",
          a2: "var(--info-a2)",
          a3: "var(--info-a3)",
          a4: "var(--info-a4)",
          a5: "var(--info-a5)",
          a6: "var(--info-a6)",
          a7: "var(--info-a7)",
          a8: "var(--info-a8)",
          a9: "var(--info-a9)",
          a10: "var(--info-a10)",
          a11: "var(--info-a11)",
          a12: "var(--info-a12)",
          contrast: "var(--info-contrast)",
          surface: "var(--info-surface)",
          indicator: "var(--info-indicator)",
          track: "var(--info-track)",
        },
        success: {
          1: "var(--success-1)",
          2: "var(--success-2)",
          3: "var(--success-3)",
          4: "var(--success-4)",
          5: "var(--success-5)",
          6: "var(--success-6)",
          7: "var(--success-7)",
          8: "var(--success-8)",
          9: "var(--success-9)",
          10: "var(--success-10)",
          11: "var(--success-11)",
          12: "var(--success-12)",
          a1: "var(--success-a1)",
          a2: "var(--success-a2)",
          a3: "var(--success-a3)",
          a4: "var(--success-a4)",
          a5: "var(--success-a5)",
          a6: "var(--success-a6)",
          a7: "var(--success-a7)",
          a8: "var(--success-a8)",
          a9: "var(--success-a9)",
          a10: "var(--success-a10)",
          a11: "var(--success-a11)",
          a12: "var(--success-a12)",
          contrast: "var(--success-contrast)",
          surface: "var(--success-surface)",
          indicator: "var(--success-indicator)",
          track: "var(--success-track)",
        },
        danger: {
          1: "var(--danger-1)",
          2: "var(--danger-2)",
          3: "var(--danger-3)",
          4: "var(--danger-4)",
          5: "var(--danger-5)",
          6: "var(--danger-6)",
          7: "var(--danger-7)",
          8: "var(--danger-8)",
          9: "var(--danger-9)",
          10: "var(--danger-10)",
          11: "var(--danger-11)",
          12: "var(--danger-12)",
          a1: "var(--danger-a1)",
          a2: "var(--danger-a2)",
          a3: "var(--danger-a3)",
          a4: "var(--danger-a4)",
          a5: "var(--danger-a5)",
          a6: "var(--danger-a6)",
          a7: "var(--danger-a7)",
          a8: "var(--danger-a8)",
          a9: "var(--danger-a9)",
          a10: "var(--danger-a10)",
          a11: "var(--danger-a11)",
          a12: "var(--danger-a12)",
          contrast: "var(--danger-contrast)",
          surface: "var(--danger-surface)",
          indicator: "var(--danger-indicator)",
          track: "var(--danger-track)",
        },
        warning: {
          1: "var(--warning-1)",
          2: "var(--warning-2)",
          3: "var(--warning-3)",
          4: "var(--warning-4)",
          5: "var(--warning-5)",
          6: "var(--warning-6)",
          7: "var(--warning-7)",
          8: "var(--warning-8)",
          9: "var(--warning-9)",
          10: "var(--warning-10)",
          11: "var(--warning-11)",
          12: "var(--warning-12)",
          a1: "var(--warning-a1)",
          a2: "var(--warning-a2)",
          a3: "var(--warning-a3)",
          a4: "var(--warning-a4)",
          a5: "var(--warning-a5)",
          a6: "var(--warning-a6)",
          a7: "var(--warning-a7)",
          a8: "var(--warning-a8)",
          a9: "var(--warning-a9)",
          a10: "var(--warning-a10)",
          a11: "var(--warning-a11)",
          a12: "var(--warning-a12)",
          contrast: "var(--warning-contrast)",
          surface: "var(--warning-surface)",
          indicator: "var(--warning-indicator)",
          track: "var(--warning-track)",
        },
        black: {
          a1: "var(--black-a1)",
          a2: "var(--black-a2)",
          a3: "var(--black-a3)",
          a4: "var(--black-a4)",
          a5: "var(--black-a5)",
          a6: "var(--black-a6)",
          a7: "var(--black-a7)",
          a8: "var(--black-a8)",
          a9: "var(--black-a9)",
          a10: "var(--black-a10)",
          a11: "var(--black-a11)",
          a12: "var(--black-a12)",
        },
        white: {
          a1: "var(--white-a1)",
          a2: "var(--white-a2)",
          a3: "var(--white-a3)",
          a4: "var(--white-a4)",
          a5: "var(--white-a5)",
          a6: "var(--white-a6)",
          a7: "var(--white-a7)",
          a8: "var(--white-a8)",
          a9: "var(--white-a9)",
          a10: "var(--white-a10)",
          a11: "var(--white-a11)",
          a12: "var(--white-a12)",
        },
      },
    },
  },
  plugins: [],
  presets: [defaultThemePreset],
} satisfies Config
