import { clsx, type ClassValue } from "clsx"
import { extendTailwindMerge } from "tailwind-merge"

const customTwMerge = extendTailwindMerge({
  extend: {
    theme: {
      color: [
        "primary-1",
        "primary-2",
        "primary-3",
        "primary-4",
        "primary-5",
        "primary-6",
        "primary-7",
        "primary-8",
        "primary-9",
        "primary-10",
        "primary-11",
        "primary-12",
        "primary-contrast",
        "primary-a1",
        "primary-a2",
        "primary-a3",
        "primary-a4",
        "primary-a5",
        "primary-a6",
        "primary-a7",
        "primary-a8",
        "primary-a9",
        "primary-a10",
        "primary-a11",
        "primary-a12",
        "secondary-1",
        "secondary-2",
        "secondary-3",
        "secondary-4",
        "secondary-5",
        "secondary-6",
        "secondary-7",
        "secondary-8",
        "secondary-9",
        "secondary-10",
        "secondary-11",
        "secondary-12",
        "secondary-contrast",
        "secondary-a1",
        "secondary-a2",
        "secondary-a3",
        "secondary-a4",
        "secondary-a5",
        "secondary-a6",
        "secondary-a7",
        "secondary-a8",
        "secondary-a9",
        "secondary-a10",
        "secondary-a11",
        "secondary-a12",
        "surface-1",
        "surface-2",
        "surface-3",
        "surface-4",
        "surface-5",
        "surface-6",
        "surface-7",
        "surface-8",
        "surface-9",
        "surface-10",
        "surface-11",
        "surface-12",
        "surface-contrast",
        "surface-a1",
        "surface-a2",
        "surface-a3",
        "surface-a4",
        "surface-a5",
        "surface-a6",
        "surface-a7",
        "surface-a8",
        "surface-a9",
        "surface-a10",
        "surface-a11",
        "surface-a12",
        "black-a1",
        "black-a2",
        "black-a3",
        "black-a4",
        "black-a5",
        "black-a6",
        "black-a7",
        "black-a8",
        "black-a9",
        "black-a10",
        "black-a11",
        "black-a12",
        "white-a1",
        "white-a2",
        "white-a3",
        "white-a4",
        "white-a5",
        "white-a6",
        "white-a7",
        "white-a8",
        "white-a9",
        "white-a10",
        "white-a11",
        "white-a12",
      ],
      text: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
      radius: ["none", "xs", "sm", "md", "lg", "xl", "2xl", "3xl", "full"],
    },
    classGroups: {
      h: [
        "h-base-input-size-1",
        "h-base-input-size-2",
        "h-base-input-size-3",
        "h-base-input-size-4",
        "h-base-toggle-size-1",
        "h-base-toggle-size-2",
        "h-base-toggle-size-3",
        "h-base-toggle-size-4",
        "h-base-button-size-1",
        "h-base-button-size-2",
        "h-base-button-size-3",
        "h-base-button-size-4",
      ],
      w: [
        "w-base-toggle-size-1",
        "w-base-toggle-size-2",
        "w-base-toggle-size-3",
        "w-base-toggle-size-4",
      ],
    },
  },
})

export function cn(...inputs: ClassValue[]) {
  return customTwMerge(clsx(inputs))
}